export default {
  pages: [
    'pages/dashboard/index',
    'pages/action-sheet/index',
    'pages/button/index',
    'pages/badge/index',
    'pages/card/index',
    'pages/cell/index',
    'pages/col/index',
    'pages/count-down/index',
    'pages/dialog/index',
    'pages/field/index',
    'pages/icon/index',
    'pages/image/index',
    'pages/loading/index',
    'pages/nav-bar/index',
    'pages/notice-bar/index',
    'pages/notify/index',
    'pages/popover/index',
    'pages/popup/index',
    'pages/progress/index',
    'pages/stepper/index',
    'pages/steps/index',
    'pages/sticky/index',
    'pages/switch/index',
    'pages/search/index',
    'pages/slider/index',
    'pages/sidebar/index',
    'pages/tabs/index',
    'pages/tabbar/index',
    'pages/tag/index',
    'pages/toast/index',
    'pages/transition/index',
    'pages/tree-select/index',
    'pages/area/index',
    'pages/submit-bar/index',
    'pages/sku/index',
    'pages/radio/index',
    'pages/checkbox/index',
    'pages/goods-action/index',
    'pages/swipe-cell/index',
    'pages/uploader/index',
    'pages/datetime-picker/index',
    'pages/rate/index',
    'pages/collapse/index',
    'pages/picker/index',
    'pages/overlay/index',
    'pages/pagination/index',
    'pages/circle/index',
    'pages/grid/index',
    'pages/dropdown-menu/index',
    'pages/index-bar/index',
    'pages/skeleton/index',
    'pages/divider/index',
    'pages/empty/index',
    'pages/calendar/index',
    'pages/share-sheet/index',
    'pages/config-provider/index',
    'pages/form/index',
    'pages/list/index',
    'pages/contact/index',
    'pages/address/index',
    'pages/cascader/index',
    'pages/swiper/index',
    'pages/pin-nav/index',
  ],
  window: {
    navigationBarBackgroundColor: '#f8f8f8',
    navigationBarTitleText: 'taro-vant',
    navigationBarTextStyle: 'black',
    backgroundTextStyle: 'dark',
    backgroundColor: '#f8f8f8',
  },
  sitemapLocation: 'sitemap.json',
}
